version: '3'
vars:
tasks:
  default:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - nix-instantiate --eval --strict
    silent: true
  pkg:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - nix-instantiate --eval --strict --arg pkgs 'import <nixpkgs> {}'
    silent: true
