version: '3'
vars:
tasks:
  default:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - nix-instantiate --eval --strict
    silent: false
  pkg:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - nix-instantiate --eval --strict --arg pkgs 'import <nixpkgs> {}'
    silent: false
  lib:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - nix-instantiate --eval --strict --arg lib '(import <nixpkgs> {}).lib'
    silent: false
